
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2

disabled_rules:
  - trailing_whitespace
  - vertical_whitespace

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

